In [1]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv("Titanic-Dataset.csv")

df[["Name"]].head()

                                                Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                           Allen, Mr. William Henry

## Text Column Used in This Notebook

The Titanic dataset does not contain customer reviews, comments, or documents.

However, the `Name` column contains textual information about passengers.

Example:

`Braund, Mr. Owen Harris`

Therefore, `Name` will be used to demonstrate basic text feature engineering.

For Bag of Words, TF-IDF, and N-Grams, a small general text example will also be used because passenger names are too short to meaningfully demonstrate document-level text representations.

This keeps the Titanic dataset consistent while demonstrating the required NLP techniques.

In [2]:
df["Name"].head(10).tolist()

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master. Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Nasser, Mrs. Nicholas (Adele Achem)']

## 1. Text Length

Text length measures the total number of characters in a text value.

### Feature Name
`Name_Text_Length`

### Source Column
- `Name`

### Logic
Count the total number of characters in the passenger name.

### Reason
Text length can provide information about the structure and complexity of text.

### Business Meaning
In customer reviews, longer text may indicate more detailed feedback.

### ML Relevance
Text length can help a model distinguish between short and detailed text.

### Leakage Check
The target variable is not used.

### Final Decision
**Retain**

In [3]:
df["Name_Text_Length"] = df["Name"].fillna("").str.len()

df[["Name", "Name_Text_Length"]].head(10)

                                                Name  Name_Text_Length
0                            Braund, Mr. Owen Harris                23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...                51
2                             Heikkinen, Miss. Laina                22
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)                44
4                           Allen, Mr. William Henry                24
5                                   Moran, Mr. James                16
6                            McCarthy, Mr. Timothy J                23
7                     Palsson, Master. Gosta Leonard                30
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)                49
9                Nasser, Mrs. Nicholas (Adele Achem)                35

## 2. Character Count

Character count measures the number of characters in the text.

For the `Name` column, this is similar to text length.

### Feature Name
`Name_Character_Count`

### Source Column
- `Name`

### Logic
Count characters in each passenger name.

### Reason
Character-level information can help describe text structure.

### Business Meaning
In a review dataset, character count represents the length of a customer's written feedback.

### ML Relevance
It can be used as a simple numerical text feature.

### Leakage Check
No target information is used.

### Final Decision
**Needs Further Analysis**

It may be redundant with `Name_Text_Length`, so both features do not necessarily need to be retained.

In [4]:
df["Name_Character_Count"] = df["Name"].fillna("").str.len()

df[["Name", "Name_Character_Count"]].head(10)

                                                Name  Name_Character_Count
0                            Braund, Mr. Owen Harris                    23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...                    51
2                             Heikkinen, Miss. Laina                    22
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)                    44
4                           Allen, Mr. William Henry                    24
5                                   Moran, Mr. James                    16
6                            McCarthy, Mr. Timothy J                    23
7                     Palsson, Master. Gosta Leonard                    30
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)                    49
9                Nasser, Mrs. Nicholas (Adele Achem)                    35

## 3. Word Count

Word count measures the number of words in a text.

### Feature Name
`Name_Word_Count`

### Source Column
- `Name`

### Logic
Split the name into words and count them.

### Reason
Word count provides information about text structure.

### Business Meaning
For customer feedback, word count represents how detailed the written response is.

### ML Relevance
It can help distinguish short and long text inputs.

### Leakage Check
No target information is used.

### Final Decision
**Retain**

In [5]:
df["Name_Word_Count"] = df["Name"].fillna("").str.split().str.len()

df[["Name", "Name_Word_Count"]].head(10)

                                                Name  Name_Word_Count
0                            Braund, Mr. Owen Harris                4
1  Cumings, Mrs. John Bradley (Florence Briggs Th...                7
2                             Heikkinen, Miss. Laina                3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)                7
4                           Allen, Mr. William Henry                4
5                                   Moran, Mr. James                3
6                            McCarthy, Mr. Timothy J                4
7                     Palsson, Master. Gosta Leonard                4
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)                7
9                Nasser, Mrs. Nicholas (Adele Achem)                5

## 4. Sentence Count

Sentence count measures the number of sentences in a text.

### Feature Name
`Name_Sentence_Count`

### Source Column
- `Name`

### Logic
Count sentence-ending punctuation such as `.`, `!`, and `?`.

Since passenger names normally do not contain complete sentences, most values will be zero.

### Reason
Demonstrate how sentence-level information can be extracted from raw text.

### Business Meaning
In reviews or customer messages, sentence count can represent how extensively a person communicates.

### ML Relevance
Sentence count can be used as a structural text feature.

### Leakage Check
No target information is used.

### Final Decision
**Needs Further Analysis**

In [6]:
df["Name_Sentence_Count"] = (
    df["Name"]
    .fillna("")
    .str.count(r"[.!?]")
)

df[["Name", "Name_Sentence_Count"]].head(10)

                                                Name  Name_Sentence_Count
0                            Braund, Mr. Owen Harris                    1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...                    1
2                             Heikkinen, Miss. Laina                    1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)                    1
4                           Allen, Mr. William Henry                    1
5                                   Moran, Mr. James                    1
6                            McCarthy, Mr. Timothy J                    1
7                     Palsson, Master. Gosta Leonard                    1
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)                    1
9                Nasser, Mrs. Nicholas (Adele Achem)                    1

## 5. Number of Digits

This feature counts the number of numerical digits appearing in the text.

### Feature Name
`Name_Digit_Count`

### Source Column
- `Name`

### Logic
Count characters from 0 to 9.

### Reason
Numbers can provide useful information in text.

### Business Meaning
In customer messages, digits may represent order numbers, prices, dates, or quantities.

### ML Relevance
Digit frequency can help text classification models identify numerical patterns.

### Leakage Check
No target information is used.

### Final Decision
**Needs Further Analysis**

In [7]:
df["Name_Digit_Count"] = df["Name"].fillna("").str.count(r"\d")

df[["Name", "Name_Digit_Count"]].head(10)

                                                Name  Name_Digit_Count
0                            Braund, Mr. Owen Harris                 0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...                 0
2                             Heikkinen, Miss. Laina                 0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)                 0
4                           Allen, Mr. William Henry                 0
5                                   Moran, Mr. James                 0
6                            McCarthy, Mr. Timothy J                 0
7                     Palsson, Master. Gosta Leonard                 0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)                 0
9                Nasser, Mrs. Nicholas (Adele Achem)                 0

## 6. Number of Special Characters

Special character count measures characters such as:

`,`, `.`, `-`, `(`, `)`, `@`, `#`, and other non-alphanumeric symbols.

### Feature Name
`Name_Special_Character_Count`

### Source Column
- `Name`

### Logic
Count characters that are not letters, numbers, or whitespace.

### Reason
Special characters can provide information about text structure.

### Business Meaning
In reviews or social media text, special-character usage may represent formatting or writing style.

### ML Relevance
Can provide additional information for text classification.

### Leakage Check
No target information is used.

### Final Decision
**Needs Further Analysis**

In [8]:
df["Name_Special_Character_Count"] = (
    df["Name"]
    .fillna("")
    .str.count(r"[^A-Za-z0-9\s]")
)

df[["Name", "Name_Special_Character_Count"]].head(10)

,Name,Name_Special_Character_Count
0,"Braund, Mr. Owen Harris",2
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",4
2,"Heikkinen, Miss. Laina",2
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4
4,"Allen, Mr. William Henry",2
5,"Moran, Mr. James",2
6,"McCarthy, Mr. Timothy J",2
7,"Palsson, Master. Gosta Leonard",2
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",4
9,"Nasser, Mrs. Nicholas (Adele Achem)",4

## 7. Uppercase Count

Uppercase count measures the number of uppercase letters in the text.

### Feature Name
`Name_Uppercase_Count`

### Source Column
- `Name`

### Logic
Count uppercase alphabetic characters.

### Reason
Uppercase usage can provide information about writing style.

### Business Meaning
In customer messages, excessive uppercase text may indicate emphasis.

### ML Relevance
Can provide a useful stylistic feature for some text classification tasks.

### Leakage Check
No target information is used.

### Final Decision
**Needs Further Analysis**

In [9]:
df["Name_Uppercase_Count"] = df["Name"].fillna("").str.count(r"[A-Z]")

df[["Name", "Name_Uppercase_Count"]].head(10)

                                                Name  Name_Uppercase_Count
0                            Braund, Mr. Owen Harris                     4
1  Cumings, Mrs. John Bradley (Florence Briggs Th...                     7
2                             Heikkinen, Miss. Laina                     3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)                     7
4                           Allen, Mr. William Henry                     4
5                                   Moran, Mr. James                     3
6                            McCarthy, Mr. Timothy J                     5
7                     Palsson, Master. Gosta Leonard                     4
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)                     7
9                Nasser, Mrs. Nicholas (Adele Achem)                     5

## 8. Lowercase Count

Lowercase count measures the number of lowercase letters in the text.

### Feature Name
`Name_Lowercase_Count`

### Source Column
- `Name`

### Logic
Count lowercase alphabetic characters.

### Reason
It describes the amount of normal lowercase text.

### Business Meaning
In written feedback, lowercase usage can describe writing patterns.

### ML Relevance
Can be used as a basic stylistic text feature.

### Leakage Check
No target information is used.

### Final Decision
**Needs Further Analysis**

In [10]:
df["Name_Lowercase_Count"] = df["Name"].fillna("").str.count(r"[a-z]")

df[["Name", "Name_Lowercase_Count"]].head(10)

                                                Name  Name_Lowercase_Count
0                            Braund, Mr. Owen Harris                    14
1  Cumings, Mrs. John Bradley (Florence Briggs Th...                    34
2                             Heikkinen, Miss. Laina                    15
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)                    27
4                           Allen, Mr. William Henry                    15
5                                   Moran, Mr. James                     9
6                            McCarthy, Mr. Timothy J                    13
7                     Palsson, Master. Gosta Leonard                    21
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)                    32
9                Nasser, Mrs. Nicholas (Adele Achem)                    22

## 9. Keyword Count

Keyword count measures how many times a specific keyword appears in a text.

### Feature Name
`Name_Mr_Count`

### Source Column
- `Name`

### Logic
Count occurrences of the keyword `Mr`.

### Reason
Keyword frequency can provide useful information when specific words are meaningful.

### Business Meaning
In customer reviews, keywords such as "refund", "delivery", or "damaged" could represent important topics.

### ML Relevance
Keyword-based features can help a model identify text patterns associated with a class or topic.

### Leakage Check
The keyword feature itself does not use the target. However, keywords should be selected without looking at test-set outcomes.

### Final Decision
**Needs Further Analysis**

In [11]:
df["Name_Mr_Count"] = (
    df["Name"]
    .fillna("")
    .str.lower()
    .str.count(r"\bmr\b")
)

df[["Name", "Name_Mr_Count"]].head(10)

                                                Name  Name_Mr_Count
0                            Braund, Mr. Owen Harris              1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...              0
2                             Heikkinen, Miss. Laina              0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)              0
4                           Allen, Mr. William Henry              1
5                                   Moran, Mr. James              1
6                            McCarthy, Mr. Timothy J              1
7                     Palsson, Master. Gosta Leonard              0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)              0
9                Nasser, Mrs. Nicholas (Adele Achem)              0

## 10. Bag of Words

Bag of Words (BoW) converts text into numerical features based on word occurrence.

It creates a vocabulary from the available documents.

Each document is represented by the number of times each vocabulary word appears.

### Example

Documents:

1. `good product`
2. `good service`
3. `bad service`

Possible vocabulary:

- good
- product
- service
- bad

Each document can then be represented as a numerical vector.

### Advantages

- Simple
- Easy to understand
- Useful for basic text classification

### Limitations

- Ignores word order
- Can create many features
- Produces sparse matrices
- Does not capture semantic meaning

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "good product",
    "good service",
    "bad service",
    "good product service"
]

vectorizer = CountVectorizer()

bow_matrix = vectorizer.fit_transform(documents)

bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

bow_df

   bad  good  product  service
0    0     1        1        0
1    0     1        0        1
2    1     0        0        1
3    0     1        1        1

## 11. TF-IDF

TF-IDF stands for Term Frequency–Inverse Document Frequency.

It assigns higher importance to words that are frequent in a particular document but less common across all documents.

### Main Idea

A word that appears in every document is usually less informative.

A word that appears in only a few documents may be more useful for distinguishing those documents.

### Advantages

- Reduces importance of very common words
- Useful for text classification
- Produces numerical text representations

### Limitations

- Does not understand semantic meaning
- Can produce many features
- Requires suitable preprocessing

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out()
)

tfidf_df.round(3)

     bad   good  product  service
0  0.000  0.629    0.777    0.000
1  0.000  0.707    0.000    0.707
2  0.843  0.000    0.000    0.538
3  0.000  0.533    0.658    0.533

## 12. N-Grams

N-Grams are sequences of consecutive words or tokens.

Types include:

- Unigram → one word
- Bigram → two words
- Trigram → three words

### Example

Text:

`very good product`

Unigrams:

- very
- good
- product

Bigrams:

- very good
- good product

Trigrams:

- very good product

### Why Use N-Grams?

N-Grams preserve some word-order information that Bag of Words loses.

For example:

`not good`

has a different meaning from:

`good`

A bigram can capture the phrase `not good`.

### Limitation

Higher-order N-Grams can significantly increase the number of features and model complexity.

In [15]:
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2))

bigram_matrix = bigram_vectorizer.fit_transform(documents)

bigram_df = pd.DataFrame(
    bigram_matrix.toarray(),
    columns=bigram_vectorizer.get_feature_names_out()
)

bigram_df

,bad,bad service,good,good product,good service,product,product service,service
0,0,0,1,1,0,1,0,0
1,0,0,1,0,1,0,0,1
2,1,1,0,0,0,0,0,1
3,0,0,1,1,0,1,1,1

## 13. Text Feature Comparison

| Technique | Representation | Main Use |
|---|---|---|
| Text Length | Number of characters | Text size |
| Character Count | Character frequency/count | Text structure |
| Word Count | Number of words | Text size |
| Sentence Count | Number of sentences | Text structure |
| Digit Count | Number of digits | Numerical patterns |
| Special Character Count | Number of special characters | Writing structure |
| Uppercase Count | Number of uppercase letters | Writing style |
| Lowercase Count | Number of lowercase letters | Writing style |
| Keyword Count | Number of keyword occurrences | Topic/pattern detection |
| Bag of Words | Word occurrence vectors | Basic NLP |
| TF-IDF | Weighted word vectors | Text classification |
| N-Grams | Word/token sequences | Capture short phrases |

Raw text must be converted into numerical representations before it can be directly used by most traditional Machine Learning algorithms.

In [16]:
text_features = [
    "Name_Text_Length",
    "Name_Character_Count",
    "Name_Word_Count",
    "Name_Sentence_Count",
    "Name_Digit_Count",
    "Name_Special_Character_Count",
    "Name_Uppercase_Count",
    "Name_Lowercase_Count",
    "Name_Mr_Count"
]

df[text_features].head(10)

,Name_Text_Length,Name_Character_Count,Name_Word_Count,Name_Sentence_Count,Name_Digit_Count,Name_Special_Character_Count,Name_Uppercase_Count,Name_Lowercase_Count,Name_Mr_Count
0,23,23,4,1,0,2,4,14,1
1,51,51,7,1,0,4,7,34,0
2,22,22,3,1,0,2,3,15,0
3,44,44,7,1,0,4,7,27,0
4,24,24,4,1,0,2,4,15,1
5,16,16,3,1,0,2,3,9,1
6,23,23,4,1,0,2,5,13,1
7,30,30,4,1,0,2,4,21,0
8,49,49,7,1,0,4,7,32,0
9,35,35,5,1,0,4,5,22,0

## Required Feature Documentation

### Feature: Name_Text_Length

**Feature Name:** Name_Text_Length  
**Source Columns:** Name  
**Logic:** Count characters in the name.  
**Reason:** Measure text length.  
**Business Meaning:** Represents the size of a text entry.  
**ML Relevance:** Can provide a simple text-length signal.  
**Leakage Check:** Target is not used.  
**Final Decision:** Retain

### Feature: Name_Word_Count

**Feature Name:** Name_Word_Count  
**Source Columns:** Name  
**Logic:** Count words in the name.  
**Reason:** Measure text structure.  
**Business Meaning:** Represents the number of words in a text entry.  
**ML Relevance:** Provides a simple text complexity feature.  
**Leakage Check:** Target is not used.  
**Final Decision:** Retain

### Feature: Name_Mr_Count

**Feature Name:** Name_Mr_Count  
**Source Columns:** Name  
**Logic:** Count occurrences of the keyword `Mr`.  
**Reason:** Demonstrate keyword-based feature engineering.  
**Business Meaning:** Represents the occurrence of a specific title/keyword.  
**ML Relevance:** Keyword presence can provide useful categorical or numerical information.  
**Leakage Check:** Target is not directly used. Keyword selection should not be based on test outcomes.  
**Final Decision:** Needs Further Analysis

### Bag of Words

**Feature Name:** BoW Features  
**Source Columns:** Text documents  
**Logic:** Convert word occurrences into numerical vectors.  
**Reason:** Represent text numerically.  
**Business Meaning:** Represents word occurrence patterns.  
**ML Relevance:** Useful for text classification and NLP tasks.  
**Leakage Check:** Vocabulary must be learned from training data only.  
**Final Decision:** Retain

### TF-IDF

**Feature Name:** TF-IDF Features  
**Source Columns:** Text documents  
**Logic:** Weight words according to their importance within and across documents.  
**Reason:** Reduce the importance of common words.  
**Business Meaning:** Represents informative terms in documents.  
**ML Relevance:** Useful for text classification and information retrieval.  
**Leakage Check:** TF-IDF vocabulary and statistics must be fitted on training data only.  
**Final Decision:** Retain

### N-Grams

**Feature Name:** N-Gram Features  
**Source Columns:** Text documents  
**Logic:** Create sequences of consecutive words/tokens.  
**Reason:** Capture short phrases and word-order information.  
**Business Meaning:** Represents combinations of words.  
**ML Relevance:** Can improve text classification by capturing phrases.  
**Leakage Check:** N-Gram vocabulary must be learned from training data only.  
**Final Decision:** Needs Further Analysis

In [17]:
documentation = pd.DataFrame({
    "Feature Name": [
        "Name_Text_Length",
        "Name_Word_Count",
        "Name_Mr_Count",
        "Bag of Words",
        "TF-IDF",
        "N-Grams"
    ],
    "Source Columns": [
        "Name",
        "Name",
        "Name",
        "Text Documents",
        "Text Documents",
        "Text Documents"
    ],
    "Leakage Check": [
        "No target used",
        "No target used",
        "No direct target usage",
        "Fit vocabulary on training data only",
        "Fit vocabulary/statistics on training data only",
        "Fit vocabulary on training data only"
    ],
    "Final Decision": [
        "Retain",
        "Retain",
        "Needs Further Analysis",
        "Retain",
        "Retain",
        "Needs Further Analysis"
    ]
})

documentation

,Feature Name,Source Columns,Leakage Check,Final Decision
0,Name_Text_Length,Name,No target used,Retain
1,Name_Word_Count,Name,No target used,Retain
2,Name_Mr_Count,Name,No direct target usage,Needs Further Analysis
3,Bag of Words,Text Documents,Fit vocabulary on training data only,Retain
4,TF-IDF,Text Documents,Fit vocabulary/statistics on training data only,Retain
5,N-Grams,Text Documents,Fit vocabulary on training data only,Needs Further Analysis

## Advantages and Limitations of Text Feature Engineering

### Advantages

- Converts raw text into ML-readable numerical features
- Captures useful information from text
- Supports text classification
- Can identify important keywords
- Can represent word occurrence and phrase patterns

### Limitations

- Text can create a very large number of features
- Bag of Words ignores word order
- TF-IDF does not understand semantic meaning
- N-Grams can increase dimensionality
- Text preprocessing may be required
- Poorly selected features can create noise
- Data leakage can occur if the text vectorizer is fitted using the complete dataset

### Final Conclusion

Raw text cannot usually be given directly to traditional Machine Learning models.

Text feature engineering converts raw text into numerical representations such as counts, Bag of Words, TF-IDF, and N-Grams.

The appropriate technique depends on the dataset, business problem, amount of text, model, and computational requirements.

In [18]:
print("Text feature engineering completed.")

print("\nBasic text features:")
display(df[text_features].head())

print("\nBag of Words features:")
display(bow_df)

print("\nTF-IDF features:")
display(tfidf_df.round(3))

print("\nN-Gram features:")
display(bigram_df)

Text feature engineering completed.

Basic text features:

,Name_Text_Length,Name_Character_Count,Name_Word_Count,Name_Sentence_Count,Name_Digit_Count,Name_Special_Character_Count,Name_Uppercase_Count,Name_Lowercase_Count,Name_Mr_Count
0,23,23,4,1,0,2,4,14,1
1,51,51,7,1,0,4,7,34,0
2,22,22,3,1,0,2,3,15,0
3,44,44,7,1,0,4,7,27,0
4,24,24,4,1,0,2,4,15,1

Bag of Words features:

   bad  good  product  service
0    0     1        1        0
1    0     1        0        1
2    1     0        0        1
3    0     1        1        1

TF-IDF features:

     bad   good  product  service
0  0.000  0.629    0.777    0.000
1  0.000  0.707    0.000    0.707
2  0.843  0.000    0.000    0.538
3  0.000  0.533    0.658    0.533

N-Gram features:

,bad,bad service,good,good product,good service,product,product service,service
0,0,0,1,1,0,1,0,0
1,0,0,1,0,1,0,0,1
2,1,1,0,0,0,0,0,1
3,0,0,1,1,0,1,1,1